- .github/workflows/cicd.yml
- Dockerfile
main, develop 머지(push) 가 일어날 시 자동으로 aws 인스턴스에 배포됩니다.
Dockerfile, cicd.yml 작성하였습니다.
> [feat] #6 CICD 파이프라인 구축

- build.gradle
- src/main/java/com/kernel360/ronaldo/TemuOverflow/chat/WebClientConfig.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/chat/controller/ChatController.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/chat/dto/ChatRequest.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/chat/dto/ChatResponse.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/chat/dto/ClaudeRequest.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/chat/dto/ClaudeResponse.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/chat/service/ChatService.java
- src/main/resources/application.yml
[feat] #1 chatBot 요청 응답 API 개발
closed #1
> [feat] #1 chatBot 요청 응답 API 개발

- .github/workflows/cicd.yml
> [feat]#13 cicd 연동시 환경 변수 및 test 코드 빌드 실패 이슈 - 2

- src/main/java/com/kernel360/ronaldo/TemuOverflow/config/SecurityConfig.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/user/entity/Role.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/user/entity/User.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/user/jwt/filter/JwtAuthenticationFilter.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/user/jwt/util/JwtTokenProvider.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/user/login/filter/CustomJsonUsernamePasswordAuthenticationFilter.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/user/login/handler/LoginFailureHandler.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/user/login/handler/LoginSuccessHandler.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/user/login/service/LoginService.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/user/service/UserAuthService.java
- src/main/resources/application.yml
- jwt 로그인 기능
- 회원가입한 email, password로 로그인해서 엑세스토큰 발급되는 것 확인하였습니다.
- 엑세스 토큰으로 인증이 되는지는 아직 확인되지 않았습니다
> [feat] 로그인 기능 구현

- src/main/java/com/kernel360/ronaldo/TemuOverflow/config/SecurityConfig.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/post/controller/PostController.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/post/repository/PostRepository.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/post/service/PostService.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/user/service/UserAuthService.java
- 랜덤 에러 조회 API
- httpServletRequest에서 엑세스토큰 바탕으로 userId 반환하는 메서드
- 어떤 사용자가 요청한건지 userId가 필요하시면 userAuthService의 getUserIdFromToken을 사용하시면 됩니다.
> [Feat] 랜덤 에러(article) 조회 API 구현

- src/main/java/com/kernel360/ronaldo/TemuOverflow/post/service/PostService.java
close #9  게시판 검색 기능구현 후 (충돌수정)
> feat: 게시판 검색 기능 구현 (충돌수정)

- src/main/java/com/kernel360/ronaldo/TemuOverflow/chat/service/ChatService.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/reply/controller/ReplyController.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/reply/dto/ReplyDto.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/reply/entity/Reply.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/reply/repository/ReplyRepository.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/reply/service/ReplyService.java
> [feat] #3 Reply 기능 구현

- src/main/java/com/kernel360/ronaldo/TemuOverflow/Like/controller/LikeController.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/Like/dto/LikeArticleResponse.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/Like/dto/LikeReplyResponse.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/Like/dto/LikeRequest.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/Like/entity/LikeArticle.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/Like/entity/LikeReply.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/Like/repository/LikeArticleRepository.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/Like/repository/LikeReplyRepository.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/Like/service/LikeService.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/config/SecurityConfig.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/user/controller/UserAuthController.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/user/dto/UserSignUpResponse.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/user/service/UserAuthService.java
- src/main/resources/application.yml
- 프론트에서 Authorization을 key로 들어온 value를 가져올 수 있게 cors설정에 `configuration.addExposedHeader("Authorization");`을 추가하였음
> [Mod] cors설정에 ExposeHeader("Authorization") 추가

- src/main/java/com/kernel360/ronaldo/TemuOverflow/config/SecurityConfig.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/user/jwt/filter/JwtAuthenticationFilter.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/user/login/filter/CustomJsonUsernamePasswordAuthenticationFilter.java
- 인증(토큰검사)하지 않는 url에 /api/login, /api/register을 추가하였습니다
> [mod] 인증(토큰검사)하지 않는 url에 /api/login, /api/register 추가

- src/main/java/com/kernel360/ronaldo/TemuOverflow/chat/service/ChatService.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/reply/controller/ReplyController.java
> [fix] #28 chat api 타임아웃 시간 증가

- src/main/java/com/kernel360/ronaldo/TemuOverflow/chat/controller/ChatController.java
[fix] #28 chat api  cors annotation 제거
> [fix] #28 chat api  cors annotation 제거

- src/main/java/com/kernel360/ronaldo/TemuOverflow/chat/controller/ChatController.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/chat/service/ChatService.java
[fix[ #28 chat api  log info add
> [fix[ #28 chat api  log info add

- src/main/java/com/kernel360/ronaldo/TemuOverflow/config/SecurityConfig.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/user/jwt/filter/JwtAuthenticationFilter.java
[fix] #28 remove auth about chatapi
> [fix] #28 remove auth about chatapi

- src/main/java/com/kernel360/ronaldo/TemuOverflow/config/SecurityConfig.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/reply/controller/ReplyController.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/reply/dto/ReplyDto.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/reply/entity/Reply.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/user/jwt/filter/JwtAuthenticationFilter.java
> [feat] #35  ai reply api 추가

- src/main/java/com/kernel360/ronaldo/TemuOverflow/post/dto/PostDto.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/post/entity/Post.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/post/service/PostService.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/reply/controller/ReplyController.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/reply/dto/ReplyDto.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/reply/entity/Reply.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/reply/service/ReplyService.java
- #38 
위 PR에 변경사항이 전부 반영되지 않아 재푸시합니다.
Closed #39
> [mod] create_at, update_at 서버에서 자동으로 설정되게 수정 / 좋아요 수 반환되게 수정 / DTO 변경 (2)

- src/main/java/com/kernel360/ronaldo/TemuOverflow/post/controller/PostController.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/post/service/PostService.java
#41  페이지네이션 기능 구현 완료입니다.
확인부탁드려요.
> 페이지네이션 기능 구현

- src/main/java/com/kernel360/ronaldo/TemuOverflow/user/controller/UserAuthController.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/user/dto/GetUserResponse.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/user/service/UserAuthService.java
- 헤더에 토큰만 넣어서 요청하면 현재 로그인한 유저 정보를 반환하는 API 구현
Closed #43
> [Feat] 현재 로그인된 유저 정보 조회 API 구현

- src/main/java/com/kernel360/ronaldo/TemuOverflow/post/controller/PostController.java
closed #42 
페이 네이션 api 경로  "/page-posts" 애서 "/page" 로 변경 하였습니다.
> fix : 페이지네이션 경로 변경

- src/main/java/com/kernel360/ronaldo/TemuOverflow/post/entity/Post.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/reply/entity/Reply.java
게시글 댓글의 content가 길어도 저장되도록 `@Column(columnDefinition = "MEDIUMTEXT")`을 붙였음.
Closed #48
> [Mod] 게시글, 댓글 content MEDIUMTEXT로 수정

- src/main/java/com/kernel360/ronaldo/TemuOverflow/post/controller/PostController.java
> fix : 페이지네이션 경로 재수정

- src/main/java/com/kernel360/ronaldo/TemuOverflow/post/controller/PostController.java
> fix : 페이지네이션 경로 재재수정

- src/main/java/com/kernel360/ronaldo/TemuOverflow/chat/service/ChatService.java
> [feat] #55  ai 챗 프롬프트 업데이트

- src/main/java/com/kernel360/ronaldo/TemuOverflow/chat/dto/ClaudeRequest.java
- src/main/resources/application.yml
[feat] # 55 ai model 수정 및 tempature 변경
> [feat] # 55 ai model 수정 및 tempature 변경

- src/main/java/com/kernel360/ronaldo/TemuOverflow/post/controller/PostController.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/post/repository/PostRepository.java
- src/main/java/com/kernel360/ronaldo/TemuOverflow/post/service/PostService.java
closed#52 
페이지네이션 최신순으로 조회 할수 있도록 수정
검색기능과 통합
> fix : post 페이지네이션 수정  검색기능과 통합

- src/main/java/com/kernel360/ronaldo/TemuOverflow/post/service/PostService.java
- 내가 작성한 게시글이 아니면 조회가 되지 않는 버그 해결
> [Hotfix] 내가 작성한 게시글이 아니면 조회가 되지 않는 버그 해결

- README.md
> [docs] readme 초안 작성

- README.md
> [docs]  Update README.md
